name: Reportar error
description: Reporta un incidente
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: input
    id: modpack-version
    attributes:
      label: ModPack version
      description: Specify the version of your ModPack
      placeholder: CatLak VI 1.0.0
    validations:
      required: true
  - type: input
    id: launcher-version
    attributes:
      label: Minecraft Launcher version
      description: Specify the version of your Minecraft Official Launcher
      placeholder: 2.3.280
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: Justify your problem as completely as possible.
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: version-launcher
    attributes:
      label: Version
      description: Select your casual launcher
      options:
        - CurseForge (Recommended)
        - Minecraft Launcher
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Publish your log link
      description: Enter your log below
      render: shell
    validations:
      required: false
